# -*- coding: utf-8 -*-
"""
/***************************************************************************
 MapTilesCalculator
                                 A QGIS plugin
 Estimates the number of map tiles for a bbox and zoom levels
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-04-28
        copyright            : (C) 2020 by bojko108
        email                : bojko108@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load MapTilesCalculator class from file MapTilesCalculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .map_tiles_calculator import MapTilesCalculator
    return MapTilesCalculator(iface)
